# Workflow name
name: Unit tests

# execute on events
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

# Jobs to run
jobs:
  # this is a job
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      # set up node
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 12

        # 2: Checkout repository in the CWD
      - name: Checkout repository
        uses: actions/checkout@v2

      # 3: install NPM dependencies
      - name: Install dependencies
        run: npm install

      # 4: run test command
      - name: Run test command
        run: npm run test
